### ISSUE TITLE
2.7 NAP en MSL

### ISSUE THREAD

**Issue by baalberts** [BROprogramma/grondwatermonitoringput#10]
Waar: paragraaf 2.7.2, pagina 16
_"Op land wordt NAP gebruikt en op zee is het gebruikelijk posities uit te drukken t.o.v. het gemiddeld zeeniveau (MSL, Mean Sea Level). Er zijn nog geen ontwikkelingen die het wenselijk maken een referentiestelsel voor de verticale positie op land en zee te gaan hanteren."_

Samenvatting: tekst is niet geheel correct
Beschrijving: Het is afhankelijk van de toepassing welk systeem gebruikt wordt voor het vastleggen van verticale posities op zee. Voor navigatie is dat juist LAT (of een ander getijdevlak). Er zijn wel degelijk toepassingen die een eenduidig stelsel op zee en land wenselijk maken (bijv. kustbeheer), een dergelijk stelsel zal echter niet voor alle toepassingen gebruikt kunnen worden.

Oplossingsrichting: de alinea zou herschreven kunnen als:
“Op land wordt NAP gebruikt en op zee is het gebruikelijk de verticale positie uit te drukken t.o.v. het gemiddeld zeeniveau (MSL, Mean Sea Level) of t.o.v. LAT (Lowest Astronomical Tide). Dit laatstgenoemde stelsel wordt tevens in de kaderrichtlijn INSPIRE genoemd als voorkeursstelsel voor het uitdrukken van verticale posities op zee. De BRO staat daarom gebruik van LAT naast MSL toe.”

**Comment by MarcelReuvers** [comment]
Onder dankzegging is het tekstvoorstel onveranderd overgenomen.
