### ISSUE TITLE
2.7 Hoogte in de BRO

### ISSUE THREAD

**Issue by baalberts** [BROprogramma/grondwatermonitoringput#11]
Waar: paragraaf 2.7.2, pagina 16

Samenvatting: tekst is onduidelijk
Beschrijving: Het is mogelijk dat gebruikers de verticale positie alleen beschikbaar hebben als ellipsoïdische hoogte in ETRS89 of WGS84. Uit de tekst is niet geheel duidelijk of deze hoogten aangeboden kunnen worden aan de BRO (het lijkt van niet maar mogelijk is dit wel wenselijk). Daarnaast is het niet duidelijk of hoogten t.o.v. LAT zullen worden getransformeerd naar MSL.

Oplossingsrichting: 
Voeg een zin toe aan de alinea die dit verduidelijkt.

**Comment by MarcelReuvers** [comment]
De tekst van paragraaf 2.7.2 is aangepast op basis van de aangedragen suggesties.
