### ISSUE TITLE
1.2 Samenhang met andere documentatie

### ISSUE THREAD

**Issue by keestjaden** [BROprogramma/grondwatermonitoringput#12]
Waar: paragraaf 1.2, pagina 6/7

Hoe zit het met de samenhang tussen verschillende registratieobjecten die deels in de LV BRO staan en deels in DINOloket, hoe is dit in de architectuur zichtbaar en begrijpelijk gemaakt voor bronhouders en dataproducenten/-leveranciers? Om het vraagstuk inzichtelijk te maken een voorbeeld:

RWS verstrekt een opdracht aan een ingenieursbureau om twee grondwaternetwerken aan te leggen bij een kanaal, een sluis is verwijderd met als gevolg lagere waterstanden in het kanaal. De grondwaterstanden in de wijk ernaast worden daardoor beïnvloed en moeten de komende jaren in de gaten gehouden worden. Voor het netwerk wordt deels gebruik gemaakt van bestaande grondwatermonitoringputten. In het contract wordt opgenomen dat het ingenieursbureau de wettelijke plichten van RWS t.a.v. van (o.a.) gebruik en levering van data uitvoert, waarbij geldt dat als levering van data aan de LV BRO (nog) niet mogelijk is, deze aan DINOloket wordt aangeleverd. In september worden de eerste meetresultaten verwacht.
Het ingenieursbureau levert per 15 september de volgende resultaten aan:
LV BRO: 6 grondwatermonitoringsputten
DINOloket: 6 grondboringen
DINOloket: 2 grondwatermonitoringnetten
DINOloket: 24 meetreeksen van grondwaterstanden, waarvan 8 reeksen gemeten zijn in 2 bestaande GMP’ten

Is het mogelijk in 1 keer alle gegevens aan te leveren (waarheen?) of moet dit in 2 (of 4) verschillende batches? Moeten de bestaande GMP’ten opnieuw worden aangemeld aan de LV BRO? Hoe gaat dit geheel verwerkt worden in de beide databases, gegeven de onderlinge relaties? Een grondwatermonitoringnet in DINOloket, dat bestaat uit grondwatermonitoringsputten die in de LV BRO staan, waar grondwaterstanden aan gekoppeld zijn die in DINOloket staan? De boringen zijn nodig om locatie van de verschillende filters in de grondwatermonitoringsputten te kunnen bepalen.
De grondwatermonitoringsputten in de LV BRO zullen niet ook in DINOloket staan, dat mag immers niet.
Hoe kunnen we als gebruiker de verschillende objecten zien? Naar grondwatermonitoringsputten kunnen kijken in de LV BRO heeft immers weinig zin als daar geen standen aan hangen of als de onderlinge samenhang van het monitoringnet mist.

**Comment by MarcelReuvers** [comment]
Dit wordt in het ketenproces met elkaar besproken en zo goed als mogelijk ingericht voor de praktijk. Feit is natuurlijk wel dat overgangssituaties ongemakken met zich mee kunnen brengen.
