### ISSUE TITLE
2 Algemene kenmerken en begrippen

### ISSUE THREAD

**Issue by keestjaden** [BROprogramma/grondwatermonitoringput#13]
Waar: paragraaf 2 en verder, vanaf pagina 9

ik heb verschillende opmerkingen en vragen gesteld over het CPT-rapport, die ook gelden voor de Grondwatermonitoringput. Die ga ik hier niet herhalen, omdat ik ervan uit ga dat deze opmerkingen en vragen ook hier verwerkt zullen worden.

**Comment by MarcelReuvers** [comment]
Ze worden al bij geotechnisch sondeeronderzoek beantwoord.
