### ISSUE TITLE
3.1 Grondwatermonitoring

### ISSUE THREAD

**Issue by keestjaden** [BROprogramma/grondwatermonitoringput#14]
Waar: paragraaf 3.1 pagina 19

"Naast de monitoringnetten die onder de verantwoordelijkheid van de bestuursorganen vallen, vallen ook de monitoringnetten van de waterbedrijven, de Unie van Landschappen en Natuurmonumenten onder de basisregistratie."
Dit zijn nieuwe inzichten, welke bestuursorganen zijn hier bronhouder? De wet is immers slechts gericht op bestuursorganen.

**Comment by MarcelReuvers** [comment]
De tekst van de catalogus loopt nog achter bij de tekst van de Algemene Maatregel van Bestuur (AMvB). De AMvB is leidend en de catalogus is hierop aangepast.
