### ISSUE TITLE
Algemene vraag over Codelijsten

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/grondwatermonitoringput#15]
Kunnen codelijsten in een later stadium (operationele BRO) nog worden uitgebreid? 
Dit is vanuit oogpunt van RWS een Must-have.

**Comment by MarcelReuvers** [comment]
ja, nieuwe versies van de standaard gaan gebeuren. Een nieuwe versie op basis van een codelijst is eenvoudiger dan structuuraanpassingen.
