### ISSUE TITLE
Algemene vraag over gebruikte begrippen

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/grondwatermonitoringput#18]
De gebruikte begrippen zijn vaak lastig te plaatsen en er wordt enig denkwerk en naslagwerk vereist om duidelijkheid te krijgen. 
Voorstel is om een begrippenlijst toe te voegen, met een figuren of schema's om een en ander zeer duidelijk te maken. Voorbeelden zijn: domein, registratieobject, datatypen, attribuut, domeinmodel, registratiedomein, entiteit.

**Comment by MarcelReuvers** [comment]
Nog nadenken waar dit te doen

**Comment by lvdbrink** [comment]
Als we de algemene teksten, die in alle catalogi worden herhaald, als een apart document gaan publiceren (iets dat we overwegen) zou een begrippenlijst daar ook bij kunnen staan.
