### ISSUE TITLE
Zomer/wintertijd?

### ISSUE THREAD

**Issue by HdcM** [BROprogramma/grondwatermonitoringput#2]
Waar: Paragraaf 4.2, pagina 37
 Samenvatting: Hoe wordt gewerkt met zomer/wintertijd
 Beschrijving: Het is onduidelijk hoe rekening wordt gehouden met de zomer en wintertijd in registraties waarbij ook de tijd wordt opgeslagen
 Oplossingsrichting: Omschrijven hoe hier mee om wordt gegaan.

**Comment by MarcelReuvers** [comment]
Met de UTC kan ingeregeld worden of het zomer- (+2) of wintertijd (+1) is.

**Comment by HdcM** [comment]
Is het juist gebruik van UTC een verplichting.
