### ISSUE TITLE
BRO overschreven en niet meer beschikbaar (pagina 13)

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/grondwatermonitoringput#22]
"Bij correctie wordt het betreffende gegeven in de BRO overschreven en is de oude waarde van het gegeven niet meer beschikbaar voor de afnemers."
Opmerking: Hoe moeten we dit lezen in relatie tot artikel 13 van de wet: "een krachtens artikel 9, eerste lid, aangewezen brondocument dat is ingeschreven in het register brondocumenten, wordt daaruit niet verwijderd"?

**Comment by MarcelReuvers** [comment]
Het woord BRO is vervangen door registratie ondergrond. En de volgende zin is toegevoegd: Zou een afnemer toch willen weten wat de eerdere foute waarde was, dan moet hij het register brondocumenten ondergrond raadplegen.
