### ISSUE TITLE
Algemene vraag oevr niet in 1x nieuwe grondwatermonitoringputten en metingen aanleveren

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/grondwatermonitoringput#23]
In de huidige praktijk kunnen dataleveranciers niet in 1x nieuwe grondwatermonitoringputten en metingen aanleveren. Zij moeten dus eerst zelf unieke identificaties aan de putten geven, de gemeten waarden worden dan (tijdelijk) met die identificaties opgeslagen. Later moeten zij de door DINOloket aangeboden aanduidingen inpassen in hun bestanden. Dit zorgt niet alleen voor veel werk, maar is ook erg foutgevoelig. Daarnaast komt het met regelmaat voor dat deze omzetting niet goed is gegaan en gegevens worden terug gestuurd. Naar verwachting zal dit voorstel in de praktijk voor zeer veel administratieve lasten en daarmee kosten zorgen.
Hoe zal dit in zijn werk gaan zodra er sprake is van de BRO?

Bij correcties is er een directe relatie met #22 "BRO overschreven en niet meer beschikbaar (pagina 13)"

**Comment by MarcelReuvers** [comment]
Buiten de scope van de catalogus. Onderdeel van de transitie.
