### ISSUE TITLE
Voor rationale getallen geldt: (pagina 36)

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/grondwatermonitoringput#24]
Er wordt gesproken over he afkappen van getallen. Is afronden geen betere optie ? Worden er bijvoorbeeld waardes in Meters of kilometers uitgedrukt die op de centimeter relevant zijn?

**Comment by MarcelReuvers** [comment]
Er is bewust voor afkappen gekozen. De reden is dat de onderliggende afspraak is dat een getal bij aanlevering moet voldoen aan de gegevensdefinitie en dat wil zeggen dat er niet meer of minder cijfers achter de komma worden aangeleverd dan gespecificeerd. Dat is het fundament. Worden er meer cijfers  achter de komma aangeleverd dan moeten die extra cijfers betekenisloos zijn. Vindt de bronhouder dat ze wel betekenis hebben dan moet hij en niet de BRO  afronding doorvoeren.
