### ISSUE TITLE
Naam attribuut dataleverancier (pagina 42)

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/grondwatermonitoringput#25]
Een grondwatermonitoringput kan door een reeks van verschillende aannemers onderhouden worden. Bronhouders moet dit soort zaken om de zoveel jaar weer opnieuw aanbesteden.
Kan een onderhoudende instantie worden gewijzigd? En zo ja, hoe moet dit proces dan worden doorlopen? En zo nee, waarom niet i.r.t. genoemd argument?

**Comment by MarcelReuvers** [comment]
Ja, de onderhoudende instantie is een dynamisch attribuut. De wijzigingen moeten worden doorgegeven zodat de wijzigingen kunnen worden vastgelegd.
