### ISSUE TITLE
Naam attribuut tijdstip laatste correctie (pagina 50)

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/grondwatermonitoringput#26]
Waar is aangegeven op welke tijdstippen correcties zijn doorgevoerd? Wijzigingsbeheer moet i.v.m. met de (her-)gebruiksplicht wel inzichtelijk zijn voor bestuursorganen, Zijn de correctiegegevens inzichtelijk voor de bronhouder?

**Comment by MarcelReuvers** [comment]
Ja, deze zijn inzichtelijk voor de bronhouder
