### ISSUE TITLE
Naam entiteit  Aangeleverde verticale positie (pagina 56)

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/grondwatermonitoringput#28]
Het attribuut verticale positie bk put is niet opgenomen. I.r.t. verticale positie t.o.v. maaiveld geven deze gezamelijk informatie over bijvoorbeeld of een put is meebewogen met de bodem in de levensduur van de grondwaterminitoringput.

**Comment by MarcelReuvers** [comment]
De bovenkant van de put is niet vertikaal opgenomen. De bodemdaling tov de put is wel onder controle van de catalogus.
