### ISSUE TITLE
Kenmerk bronhouder

### ISSUE THREAD

**Issue by HdcM** [BROprogramma/grondwatermonitoringput#3]
Waar: Paragraaf 4.5, pagina 42
 Samenvatting: Relevantie KvK-nummer
 Beschrijving: Voor mij als hydroloog is van belang wie de bronhouder is, en hoe ik met deze in contact kan komen. Een contactpersoon of telefoonnummer is voor mij relevanter dan een KvK-nummer.
 Oplossingsrichting: Contact gegevens toevoegen.

**Comment by MarcelReuvers** [comment]
Zie eerdere opmerking bij geotechnisch sondeeronderzoek.
Het is overigens niet de bedoeling dat gebruikers contact opnemen met de bronhouder. Bij vragen of gerede twijfel aan de juistheid van gegevens neemt men contact op met de registerbeheerder die dan eventueel de bronhouder kan betrekken.
