### ISSUE TITLE
Kwaliteitsregime Aanlevering betreffend formaat (pagina 12)

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/grondwatermonitoringput#30]
"De introductie van de twee kwaliteitsregimes geeft de aanleverende partijen gedurende een bepaalde periode een zekere mate van vrijheid."
Opmerkingen: Voorstel is om "aanleverende partijen" te vervangen door brondhouder. De keuze van het gewenste c.q. verplichte aan te leveren kwaliteitsregime ligt in basis bij de opdractgever, zijnde de brondhouder.

**Comment by MarcelReuvers** [comment]
_aanleverende partijen_ gewijzigd in _bronhouders_
