### ISSUE TITLE
KaderAanlevering (pagina 80/81)

### ISSUE THREAD

**Issue by IwanKlein** [BROprogramma/grondwatermonitoringput#31]
Het is niet duidelijk of 1 of meerdere opties uit de codelijst kunnen worden ingevoerd. In diverse gevallen zijn 2 tot 3 mogelijkheden van toepassing. De wens c.q. noodzaak om meerdere opties in te voeren is aanwezig.

**Comment by MarcelReuvers** [comment]
De kardinaliteit is 1. Indien de juiste waarde er niet bijstaat is ons verzoek om te komen tot aanvullende domeinwaarden. De lijst kan hier op aangepast worden.
