### ISSUE TITLE
Positiebepaling algemeen

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#32]
Algemeen: positiebepaling
Samenvatting: de methode positiebepaling is gelijk aan de werkwijze die is gevolgd bij de bepaling van de positie
Beschrijving: Te overwegen is om eisen te stellen aan de nauwkeurigheid van de positiebepaling (horizontaal en verticaal). Dit om de kwaliteit/betrouwbaarheid van het object zo hoog mogelijk te duiden.
Dit geldt voor alle registratieobjecten.

**Comment by MarcelReuvers** [comment]
Dit is een opmerking die we in overweging gaan nemen voor de navolgende registratieobjecten.
