### ISSUE TITLE
Gebruiksovereenkomst Algemeen

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#33]
Algemeen: gebruiksovereenkomst
Samenvatting: gebruiksovereenkomst eigenaar/pachter perceel – eigenaar GWP
Beschrijving: aan een GMP is veelal een gebruiksovereenkomst gekoppeld ten aanzien van het gebruik/betreden van een perceel. 
Oplossingsrichting: Opname van een gebruiksovereenkomst optioneel, inclusief datum

**Comment by MarcelReuvers** [comment]
Dit is te specifiek voor de BRO en daarmee informatie die zelf in het eigen processysteem kan worden opgeslagen.
