### ISSUE TITLE
Ministerie als bronhouder

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#34]
Par 4.5. pag 42
Samenvatting: Het Ministerie IenM is bronhouder van de historische grondwaterputten afkomstig uit DINO
Beschrijving: hoe wordt deze verantwoordelijkheid gematerialiseerd met betrekking tot de verantwoordelijkheden die hiermee samenhangen. 
De opmerking geldt ook voor Geotechnisch sondeeronderzoek

**Comment by MarcelReuvers** [comment]
Het Ministerie is verantwoordelijk maar delegeert deze verantwoordelijkheid aan de beheerder van DINO. In de praktijk betekent dit dat de beheerder van DINO onjuistheden in de aangeleverde gegevens zal proberen op te lossen.
