### ISSUE TITLE
Reikwijdte grondwatermonitoringsnet

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#35]
Par 4.5, pag 41
Samenvatting: reikwijdte grondwatermonitoringsnetten
Beschrijving: Bij grondwateronttrekkingen (anders dan tbv de openbare drinkwatervoorziening) worden in het kader van de Waterwet meetnetten voorgeschreven voor langjarige meting van grondwaterstanden en – stijghoogten. De vergunninghouder is beheerder van deze meetnetten. Het is wenselijk om deze informatie via de BRO te ontsluiten.

**Comment by MarcelReuvers** [comment]
Dit onderwerp hoort thuis in de Algemene Maatregel van Bestuur en wordt daarin geadresseerd.
