### ISSUE TITLE
Putten met voorgeschiedenis

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#36]
Par 3.5, pag 30
Samenvatting: Putten met een voorgeschiedenis
Beschrijving: grondwatermonitoringputten hebben een voorgeschiedenis en omvatten een omvangrijke reeks monitoringsgegevens. 
Hoe krijgt de conversie en inname van historische monitoringsgegevens vorm?

**Comment by MarcelReuvers** [comment]
Dit krijgt later vorm bij een ander registratieobject.
