### ISSUE TITLE
Dataleverancier

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#37]
Par 4.5, pag 42
Samenvatting: naam dataleverancier
Beschrijving: Er wordt niet gevraagd naar de naam van de dataleverancier noch de naam van de betreffende medewerker die de data levert. 
Oplossingsrichting: velden creëren om beide namen toe te voegen.

**Comment by MarcelReuvers** [comment]
De naam kan via het nummer worden opgehaald. Hiermee ben je onafhankelijk van naamsverandering. Naam medewerker gaat te ver (kan natuurlijk wel in het eigen processysteem worden bijgehouden).
