### ISSUE TITLE
Tussentijdse gebeurtenis

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#38]
Par 3.1, pag 54
Samenvatting: tussentijdse gebeurtenis
Beschrijving: naam van de instantie die de gebeurtenis heeft gemeld en wie deze heeft veroorzaakt. 
Oplossingsrichting: velden toevoegen om beide te registreren.

**Comment by MarcelReuvers** [comment]
Het terugmelden is een apart proces en de gegevens (dossiers) die daar bijhoren worden buiten de registratie ondergrond vastgelegd.
