### ISSUE TITLE
Monitoringbuis nummering buizen

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#39]
Par 7, pag 60
Samenvatting: monitoring buis
Beschrijving. Een logische volgorde van voorkomende buizen. 
Oplossingsrichting: toevoegen aan de definitie: oplopende nummering van de monitoringsbuis naar toenemende diepte van het filter.  Mogelijk NEN hierop aanpassen.

**Comment by MarcelReuvers** [comment]
tekst toegevoegd (hoe dieper het filter des te hoger het nummer)
