### ISSUE TITLE
Keuze minimale meetperiode

### ISSUE THREAD

**Issue by HdcM** [BROprogramma/grondwatermonitoringput#4]
Waar: Paragraaf 3.1, pagina 19
 Samenvatting: Keuze minimale meetperiode.
 Beschrijving: De keuze om alleen meetnetten met een meetperiode van minimaal 3 jaar op te nemen leidt er toe dat -mijns inziens- relevante grondwater gegevens buiten de BRO vallen.
Oplossingsrichting: Termijn wijzigen naar 1 jaar.

**Comment by MarcelReuvers** [comment]
De tekst van de catalogus loopt nog achter bij de tekst van de Algemene Maatregel van Bestuur (AMvB). De AMvB is leidend en stelt dat de minimale periode 1 jaar is en dat bronhouders daarvan naar eigen goeddunken kunnen afwijken. De catalogus zal hierop worden aangepast.
