### ISSUE TITLE
Monitoring buis afsluitdop

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#40]
Par 7, pag 62
Samenvatting: monitoring buis
Beschrijving: Voorzien van afsluitdop. Een monitoringsbuis kan door verschillende oorzaken buiten gebruik worden gesteld, terwijl andere buizen in deze monitoringsput in gebruik blijven. 
Oplossingsrichting: een nieuw attribuut toevoegen.

**Comment by MarcelReuvers** [comment]
Dit gebeurt met het attribuut: buisstatus
