### ISSUE TITLE
Aanvulmateriaal buis

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#42]
Par 7, pag 66
Samenvatting: aanvulmateriaal buis
Beschrijving: diepteligging van het aanvulmateriaal
Oplossingsrichting: toevoegen van de bovenkant en onderkant van het aanvulmateriaal per aanvullaag.
Toelichting. Volgens de NEN dienen slechtdoorlatende lagen in het boorgat te worden hersteld met voor water slechtdoorlatend materiaal. 
Deze opmerking geldt ook voor de Geo-ohmkabel.

**Comment by MarcelReuvers** [comment]
Dit hebben we bewust niet gedaan omdat het hiermee erg veel gegevens worden.
