### ISSUE TITLE
Positie boven- en onderkant buis

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#43]
Par 7, pag 68
Samenvatting: positie bovenkant en onderkant filterbuis
Beschrijving: referentie ontbreekt
Oplossingsrichting: toevoegen: gemeten tov NAP

**Comment by MarcelReuvers** [comment]
Het wordt uitgedrukt in het lokaal referentiepunt. In dit geval is het NAP.
