### ISSUE TITLE
Ingeplaatst deel

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#44]
Par 7.5, pag 71
Samenvatting: Lengte ingeplaatst deel
Beschrijving: bij verzakking van een mantelbuis kan het nodig zijn om de stijgbuizen in te korten. Dan is sprake van inkorten van de buis en niet van inplaatsen van een deel. Deze gebeurtenis leidt werkt door in de hoogte van de buis. 
Oplossingsrichting: Toevoegen lengte ingekort deel. Aandacht voor doorrekening naar bovenkant buis.

**Comment by MarcelReuvers** [comment]
Deze informatie is gedekt. Het inkorten van de buis is een van de tussentijdse gebeurtenissen die wordt ondersteund (p. 27). Details over het betreffende brondocument staan in het Innamehandboek.
