### ISSUE TITLE
Locatiebepaling hor en vert

### ISSUE THREAD

**Issue by ClemensKester** [BROprogramma/grondwatermonitoringput#45]
Samenvatting: Methode locatiebepaling horizontaal en verticaal
Beschrijving: De waardeverzamelingen in de codelijsten voor de MethodeLocatiebepaling en MethodeVerticalePositie in de catalogi Geotechnisch sondeeronderzoek en Grondwatermonitoringput  verschillen sterk van elkaar. De verschillen zitten in de methoden onder Waardeverzameling en onder Omschrijving. Op basis waarvan zijn de verzamelingen gebaseerd? Harmonisatie is zeer gewenst op voorwaarde dat dat mogelijk is.

**Comment by MarcelReuvers** [comment]
De codelijsten die voor  de verschillende registratieobjecten waren opgesteld  verschilden onderling. Inmiddels zijn de lijsten op elkaar afgestemd zodat ongewenste verschillen zijn weggenomen.
