### ISSUE TITLE
Waardebereik maaiveld niet toereikend

### ISSUE THREAD

**Issue by BROServicedesk** [BROprogramma/grondwatermonitoringput#58]
Het maaiveld heeft volgens de catalogus een waardebereik van -10 tot 325 meter tov NAP ( Zie attribuut **5.4 maaiveldpositie** in de GMW catalogus versie 1.0).

De GMW in het DINOloket met NITG-nummer B20G0004 heeft een maaiveld van -11.7 meter tov NAP en kan niet opgenomen worden in de BRO.

Voorstel: Waardebereik maaiveld verruimen.

**Comment by fterpstra** [comment]
Ik heb de betreffende put op gezocht in DINOloket, hij ligt op een dijk in flevoland net naast de A6 ongeveer hier https://www.google.com/maps/@52.5959213,5.5752254,142m/data=!3m1!1e3 volgens mij is de waarde van het maaiveld fout. Volgens AHN is het naast de dijk -4.3 meter en op de dijk tot 5meter boven NAP.

**Comment by BROServicedesk** [comment]
Basisregistratie Ondergrond BM20 05 00115

Geachte ,

Uw melding is geregistreerd onder nummer BM20 05 00115.

 : Re: [BROprogramma/GMW] Waardebereik maaiveld niet toereikend (#58)
Afzender: notifications@github.com
Datum verzonden: 27-mei-2020 17:13
Naar: BROprogramma/GMW <GMW@noreply.github.com>
CC: BROServicedesk <support@broservicedesk.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [BROprogramma/GMW] Waardebereik maaiveld niet toereikend (#58)

Ik heb de betreffende put op gezocht in DINOloket, hij ligt op een dijk in flevoland net naast de A6 ongeveer hier https://www.google.com/maps/@52.5959213,5.5752254,142m/data=!3m1!1e3 volgens mij is de waarde van het maaiveld fout. Volgens AHN is het naast de dijk -4.3 meter en op de dijk tot 5meter boven NAP.
?
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[https://github.com/notifications/beacon/AOYAYRM775B64EPZPB4UF63RTUUZNA5CNFSM4NMBL5WKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEXKTKKI.gif]

Voor vragen of opmerkingen zijn wij bereikbaar via support@broservicedesk.nl.

Met vriendelijke groet,

BRO-servicedesk
Basisregistratie Ondergrond

**Comment by VianaAchthoven** [comment]
Op basis van terugkoppeling van Erik Simmelink wordt de call gesloten op basis van het volgende:

Na een nadere beschouwing van de put-casus die heeft geleid tot deze beheer-issue werd geconcludeerd dat er sprake is van een onterecht verzoek tot aanpassing van het waardebereik van de maaiveldhoogte. Het betreft daarmee geen GMW beheer-issue/ het beheer BRO standaarden.

Vastgesteld is dat in tegenstelling tot eerdere analyse, er wel sprake moet zijn van een foutief, in DINO geregistreerde maaiveldhoogte waarde ( -11.7 m tov NAP). De put staat op een dijk in Flevoland, die al was aangelegd ten tijde van de inrichting van de put. Ook andere gegevens in DINO (hoogte bovenkant van de buis) bevestigen dat dat de werkelijke maaiveldhoogte boven NAP moet liggen. En ook al lag ten tijde van de putinrichting.

De terugkoppeling en sluiting van BM20 05 00115 wordt in de BRO-servicedesk omgeving wordt door Megan afgehandeld.

**Comment by BROServicedesk** [comment]
Basisregistratie Ondergrond BM20 06 00017

Geachte ,

Uw melding is geregistreerd onder nummer BM20 06 00017.

 : Re: [BROprogramma/GMW] Waardebereik maaiveld niet toereikend (#58)
Afzender: notifications@github.com
Datum verzonden: 4-jun-2020 9:03
Naar: BROprogramma/GMW <GMW@noreply.github.com>
CC: BROServicedesk <support@broservicedesk.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [BROprogramma/GMW] Waardebereik maaiveld niet toereikend (#58)

Op basis van terugkoppeling van Erik Simmelink wordt de call gesloten op basis van het volgende:
Na een nadere beschouwing van de put-casus die heeft geleid tot deze beheer-issue werd geconcludeerd dat er sprake is van een onterecht verzoek tot aanpassing van het waardebereik van de maaiveldhoogte. Het betreft daarmee geen GMW beheer-issue/ het beheer BRO standaarden.
Vastgesteld is dat in tegenstelling tot eerdere analyse, er wel sprake moet zijn van een foutief, in DINO geregistreerde maaiveldhoogte waarde ( -11.7 m tov NAP). De put staat op een dijk in Flevoland, die al was aangelegd ten tijde van de inrichting van de put. Ook andere gegevens in DINO (hoogte bovenkant van de buis) bevestigen dat dat de werkelijke maaiveldhoogte boven NAP moet liggen. En ook al lag ten tijde van de putinrichting.
De terugkoppeling en sluiting van BM20 05 00115 wordt in de BRO-servicedesk omgeving wordt door Megan afgehandeld.
?
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[https://github.com/notifications/beacon/AOYAYRKKAM2GBNQVW5SXYH3RU5BN7A5CNFSM4NMBL5WKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEYIPVZI.gif]

Voor vragen of opmerkingen zijn wij bereikbaar via support@broservicedesk.nl.

Met vriendelijke groet,

BRO-servicedesk
Basisregistratie Ondergrond

**Comment by BROServicedesk** [comment]
Basisregistratie Ondergrond BM20 06 00018

Geachte ,

Uw melding is geregistreerd onder nummer BM20 06 00018.

 : Re: [BROprogramma/GMW] Waardebereik maaiveld niet toereikend (#58)
Afzender: notifications@github.com
Datum verzonden: 4-jun-2020 9:04
Naar: BROprogramma/GMW <GMW@noreply.github.com>
CC: BROServicedesk <support@broservicedesk.nl>, Author <author@noreply.github.com>
Onderwerp: Re: [BROprogramma/GMW] Waardebereik maaiveld niet toereikend (#58)

Closed #58.
?
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
[https://github.com/notifications/beacon/AOYAYROWAH36F4FLDSXASWTRU5BOBA5CNFSM4NMBL5WKYY3PNVWWK3TUL52HS4DFWZEXG43VMVCXMZLOORHG65DJMZUWGYLUNFXW5KTDN5WW2ZLOORPWSZGOZL47QBQ.gif]

Voor vragen of opmerkingen zijn wij bereikbaar via support@broservicedesk.nl.

Met vriendelijke groet,

BRO-servicedesk
Basisregistratie Ondergrond
