### ISSUE TITLE
4.5 registratieobject BRO ID

### ISSUE THREAD

**Issue by rbv305** [BROprogramma/grondwatermonitoringput#6]
BRO-ID dit nummer wordt automatisch gegenereerd waardoor de grondwatermonitoringput een betekenisloze id krijgt. Dit is onwenselijk als het gaat om herkenning van de putten. Kan aan de BRO id geen omschrijving worden gekoppeld waardoor de grondwaterput herkenbaar blijft voor de gebruiker ?

**Comment by MarcelReuvers** [comment]
het gegeven putcode is toegevoegd en het gegeven  historische ID is in NITG-code veranderd
