### ISSUE TITLE
2.10 Authenticiteit en verplichte waarde

### ISSUE THREAD

**Issue by rbv305** [BROprogramma/grondwatermonitoringput#8]
gaat het bij het bepalen van de authenticiteit alleen om de putten of geldt het straks ook voor de waarden die daaraan gekoppeld worden ?
Met andere woorden worden overheden straks ook verplicht om bij het doen van onderzoek gebruik te maken van de BRO ?

**Comment by MarcelReuvers** [comment]
2 keer ja
