### ISSUE TITLE
2.7 RD, ETRS89 en WGS84

### ISSUE THREAD

**Issue by baalberts** [BROprogramma/grondwatermonitoringput#9]
Waar: paragraaf 2.7.1, pagina 15
_"Die afspraken moeten in lijn zijn met Europese afspraken en leiden tot een kleiner aantal
referentiestelsels. Concreet betekent dit dat Nederland over zal gaan op het ETRS-stelsel, en op termijn afscheid neemt van de referentiestelsels RD en WGS84."_

Samenvatting: tekst is niet geheel correct
Beschrijving: Het samenwerkingsverband tussen het Kadaster, Dienst der Hydrografie en Rijkswaterstaat (NSGI: Nederlandse Samenwerking Geodetische Infrastructuur) is verantwoordelijk voor de vastlegging en instandhouding van de nationale referentiesystemen, de relaties tussen die stelsels onderling en met de Europese systemen. Op het gebruik van stelsels en definities van internationale stelsel heeft de NSGI geen directe invloed. Afhankelijk van de toepassing zal ook in de toekomst gewerkt kunnen worden in RD of WGS84. ETRS-stelsel moet zijn ETRS89-stelsel.

Oplossingsrichting: Het is beter om bovenstaande zinnen te vervangen door:
“Die afspraken moeten in lijn zijn met Europese afspraken en leiden tot heldere en eenduidige transformatieprocedures tussen referentiestelsels. Concreet betekent dit dat in Nederland op termijn het ETRS89-stelsel als standaard zal worden gehanteerd voor het uitwisselen van geo-informatie”.

**Comment by MarcelReuvers** [comment]
Onder dankzegging is het tekstvoorstel onveranderd overgenomen.
